// We will replace this with a dynamic ID when we add Authentication later
const String TEST_HOUSEHOLD_ID = 'my-test-family';

const List<String> COMMON_INGREDIENTS = [
  // --- Proteins ---
  "Chicken Breast",
  "Chicken Thighs",
  "Whole Chicken",
  "Ground Chicken",
  "Ground Beef",
  "Beef Steak",
  "Beef Roast",
  "Beef Ribs",
  "Ground Turkey",
  "Turkey Breast",
  "Turkey Legs",
  "Pork Chops",
  "Pork Shoulder",
  "Bacon",
  "Sausage",
  "Ham",
  "Hot Dogs",
  "Salmon",
  "Shrimp",
  "Tuna",
  "Tilapia",
  "White Fish",
  "Eggs",

  // --- Dairy ---
  "Milk",
  "Butter",
  "Salted Butter",
  "Unsalted Butter",
  "Cheddar Cheese",
  "Mozzarella Cheese",
  "Parmesan",
  "Cream Cheese",
  "Yogurt",
  "Greek Yogurt",
  "Heavy Cream",
  "Sour Cream",
  "Half and Half",

  // --- Grains & Bread ---
  "Rice",
  "Brown Rice",
  "Basmati Rice",
  "Jasmine Rice",
  "Pasta",
  "Spaghetti",
  "Penne",
  "Macaroni",
  "Quinoa",
  "Couscous",
  "Bulgur",
  "Oats",
  "Bread",
  "Pita Bread",
  "Tortillas",
  "Naan",

  // --- Vegetables ---
  "Potatoes",
  "Sweet Potatoes",
  "Onions",
  "Red Onions",
  "Green Onions",
  "Garlic",
  "Tomatoes",
  "Cherry Tomatoes",
  "Bell Peppers",
  "Carrots",
  "Broccoli",
  "Cauliflower",
  "Spinach",
  "Kale",
  "Lettuce",
  "Cabbage",
  "Cucumber",
  "Zucchini",
  "Eggplant",
  "Mushrooms",
  "Corn",
  "Peas",
  "Green Beans",
  "Asparagus",
  "Celery",
  "Radishes",
  "Beets",
  "Ginger Root",

  // --- Fruits ---
  "Lemon",
  "Lime",
  "Apple",
  "Banana",
  "Orange",
  "Mandarin",
  "Strawberries",
  "Blueberries",
  "Raspberries",
  "Grapes",
  "Pineapple",
  "Watermelon",
  "Mango",
  "Peach",
  "Avocado",

  // --- Legumes ---
  "Beans",
  "Black Beans",
  "Kidney Beans",
  "Pinto Beans",
  "Lentils",
  "Red Lentils",
  "Green Lentils",
  "Chickpeas",

  // --- Fresh Herbs ---
  "Cilantro",
  "Parsley",
  "Basil",
  "Mint",
  "Rosemary",
  "Thyme",
  "Oregano",
  "Dill",
  "Sage",

  // --- Baking ---
  "Sugar",
  "Brown Sugar",
  "Powdered Sugar",
  "Flour",
  "Whole Wheat Flour",
  "Baking Powder",
  "Baking Soda",
  "Yeast",
  "Cornstarch",
  "Cocoa Powder",

  // --- Oils ---
  "Olive Oil",
  "Vegetable Oil",
  "Canola Oil",
  "Coconut Oil",
  "Avocado Oil",
  "Sesame Oil",

  // --- Sauces & Condiments ---
  "Soy Sauce",
  "Tomato Sauce",
  "Tomato Paste",
  "Ketchup",
  "Mustard",
  "Mayonnaise",
  "BBQ Sauce",
  "Hot Sauce",
  "Worcestershire Sauce",
  "Vinegar",
  "Balsamic Vinegar",
  "Apple Cider Vinegar",

  // --- Spices (big expansion) ---
  "Salt",
  "Black Pepper",
  "White Pepper",
  "Paprika",
  "Smoked Paprika",
  "Cumin",
  "Ground Coriander",
  "Turmeric",
  "Curry Powder",
  "Chili Powder",
  "Red Pepper Flakes",
  "Cinnamon",
  "Nutmeg",
  "Cardamom",
  "Cloves",
  "Allspice",
  "Bay Leaves",
  "Oregano",
  "Italian Seasoning",
  "Herbes de Provence",
  "Ginger Powder",
  "Garlic Powder",
  "Onion Powder",
  "Taco Seasoning",
  "Cajun Seasoning",
  "Five Spice",
  "Za'atar",
  "Sumac",
  "Saffron",
  "Fenugreek",
  "Mustard Seeds",
  "Fennel Seeds",
  "Caraway Seeds",
  "Curry Leaves",

  // --- Canned & Packaged ---
  "Canned Tomatoes",
  "Tomato Puree",
  "Canned Corn",
  "Canned Beans",
  "Canned Tuna",
  "Canned Chickpeas",
  "Coconut Milk",
  "Chicken Broth",
  "Beef Broth",
  "Vegetable Broth",

  // --- Drinks ---
  "Coffee",
  "Tea",
  "Green Tea",
  "Juice",
  "Sparkling Water",
];
