// We will replace this with a dynamic ID when we add Authentication later
const String TEST_HOUSEHOLD_ID = 'my-test-family';

const List<String> COMMON_INGREDIENTS = [
  "Chicken Breast",
  "Ground Beef",
  "Eggs",
  "Milk",
  "Butter",
  "Cheese",
  "Rice",
  "Pasta",
  "Bread",
  "Potatoes",
  "Onions",
  "Garlic",
  "Tomatoes",
  "Spinach",
  "Broccoli",
  "Carrots",
  "Bell Peppers",
  "Mushrooms",
  "Salt",
  "Pepper",
  "Olive Oil",
  "Vegetable Oil",
  "Soy Sauce",
  "Sugar",
  "Flour",
  "Lemon",
  "Lime",
  "Cilantro",
  "Parsley",
  "Salmon",
  "Shrimp",
  "Tuna",
  "Yogurt",
  "Heavy Cream",
  "Bacon",
  "Sausage",
  "Ham",
  "Turkey",
  "Avocado",
  "Cucumber",
  "Lettuce",
  "Corn",
  "Peas",
  "Beans",
  "Lentils",
  "Chickpeas",
];
